language: python
python:
    - "3.5"
sudo: false
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
install:
    - pip install -U pip
    - pip install -U Flask tox coverage codecov
script:
    - tox
after_success:
    - bash <(curl -s https://codecov.io/bash)
